### ISSUE TITLE
Why are some tests expected to timeout?

### ISSUE THREAD

**Issue by jsquyres** [openshmem-org/tests-uh#15]
I notice in testrunner.pl (and the various .conf files) that some tests are expected to timeout.

I'm curious: why are tests expected to time out / why does testrunner.pl report those tests as succeeding?

Thanks!

@jdinan @tonycurtis

**Comment by jdinan** [comment]
These tests are checking that the synchronizing collectives will deadlock when not called by all PEs, so they are expected to time out.

**Comment by jsquyres** [comment]
Ah, so they are *expected* deadlocks / ("failures").  Got it.

Thanks!
