### ISSUE TITLE
Inaccessibility is a lie

### ISSUE THREAD

**Issue by jdinan** [openshmem-org/tests-uh#29]
The `feature_tests/Fortran/accessibility/test_shmem_acc_mem_04_*.f90` unit tests check whether the compiler does _not_ place the following variable in the data or bss segment:
```
real*8            :: remote_dest(2)
```
However, it's totally fine for the compiler to put a program-level variable (i.e. lifetime is the duration of the full program) like this into the data segment and it turns out that ifort does just this.  The `*05*` tests are similar, except the given variable is `ALLOCATABLE`, which is a more reasonable test of inaccessibility.

I considered proposing to move the `*04*` tests to "error" tests, but I don't think they are even valid error tests.  Can we delete them?

**Comment by tonycurtis** [comment]
> On Feb 15, 2018, at 9:01 PM, James Dinan <notifications@github.com> wrote:
> 
> The feature_tests/Fortran/accessibility/test_shmem_acc_mem_04_*.f90 unit tests check whether the compiler does not place the following variable in the data or bss segment:
> 
> real*8            :: remote_dest(2)
> However, it's totally fine for the compiler to put a program-level variable (i.e. lifetime is the duration of the full program) like this into the data segment and it turns out that ifort does just this. The *05* tests are similar, except the given variable is ALLOCATABLE, which is a more reasonable test of inaccessibility.
> 
> I considered proposing to move the *04* tests to "error" tests, but I don't think they are even valid error tests. Can we delete them?
> 

yes, sure
tony

**Comment by jdinan** [comment]
Turns out those `*05*` accessibility tests are not enabled, but they seem to work fine.  Looks like an oversight..
